remote_theme: "mmistakes/minimal-mistakes@4.24.0"
#theme: jekyll-theme-cayman
title: Shengchao Lin's Homepage
locale: "en-US"
baseurl: "https://shengchao-lin.github.io"
plugins:
  - jekyll-include-cache
minimal_mistakes_skin: "dark" # "air", "aqua", "contrast", "dark", "dirt", "neon", "mint", "plum", "sunrise"
logo: "/assets/images/Logo.png"

defaults:
  # _docs
  - scope:
      path: ""
      type: docs
    values:
      sidebar:
        nav: "docs"